# Generated by Django 6.0.6 on 2026-06-16 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stat_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stat',
            new_name='star',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 6, 16, 14, 27, 54, 229887)),
        ),
    ]
