# Generated by Django 6.0.6 on 2026-07-08 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_profile_old_cart_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 7, 8, 21, 14, 59, 873068)),
        ),
    ]
